---
title: "Homework 4"
author: "Kunal Palawat"
date: "3/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question 1

x <- 1.1
a <- 2.2
b <- 3.3

z <- c(x^{a^b},
       (x^{a})^b,
       3x^3+2x^2+1)
       



Question 2
```{r}
a <- c(seq(from = 1, to = 8, by = 1),
      seq(from = 7, to = 1, by = -1))

b <- c(rep(1, 1),
       rep(2,2),
       rep(3,3),
       rep(4,4),
       rep(5,5))

c <- c(rep(5, 1),
       rep(4,2),
       rep(3,3),
       rep(2,4),
       rep(1,5))
print(a)
print(b)
print(c)
```

Question 3
```{r}
unifVec <- runif(2)
sinVec <- asin(unifVec)
print(sinVec)
```

Question 4
```{r}
queue <- c("sheep", "fox", "owl", "ant")
queueA <- c("sheep", "fox", "owl", "ant", "serpent")
queueB <- c("fox", "owl", "ant")
queueC <- c("donkey", "fox", "owl", "ant", "serpent")
queueD <- c("donkey", "fox", "owl", "ant")
queueE <- c("donkey", "fox", "ant")
queueF <- c("donkey", "fox", "aphid", "ant")
str(queueF)

```

Question 5
```{r}
z <- runif(1000)
(z<.10)
```

